GRANT USAGE ON *.* TO 'myaccount_game'@'%' IDENTIFIED BY PASSWORD '*DF74B72223909315C30BDCBE116CFE4007ED170F';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE ON `myaccount`.* TO 'myaccount_game'@'%';


GRANT USAGE ON *.* TO 'mylife_game'@'%' IDENTIFIED BY PASSWORD '*AC9D1E5A714BB363706B62E792EEDC29ACEE08A2';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE ON `mylife_player`.* TO 'mylife_game'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE ON `mylife_static`.* TO 'mylife_game'@'%';

